### ISSUE TITLE
Configure fix for user supplied LAPACK & BLAS

### ISSUE THREAD

**Issue by jfrench7** [pv/arpack-ng#2]
Hi,
When compiling ARPACK using my own LAPACK & BLAS libs, "make" could not find several BLAS libraries called by LAPACK.  It turns out several makefiles have
$(BLAS_LIBS) $(LAPACK_LIBS)

Please reverse the order to:
$(LAPACK_LIBS) $(BLAS_LIBS)

As Lapack depends on on BLAS.

Thanks!

**Comment by pv** [comment]
This is my personal fork of arpack-ng --- the actual project is here: https://github.com/opencollab/arpack-ng
